name:                aoc
version:             0.1.0.0
github:              "drewolson/aoc-hs"
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2022-present Drew Olson"

description: Advent of Code in Haskell

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- hashable
- hashtables
- hspec
- hspec-discover
- matrix
- megaparsec
- multiset
- optparse-applicative
- parallel
- raw-strings-qq
- search-algorithms
- split

library:
  source-dirs: src

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - QuasiQuotes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    when:
    - condition: false
      other-modules: Paths_aoc
