name:                aoc
version:             0.1.0.0
github:              "drewolson/aoc-hs"
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2021 Drew Olson"

extra-source-files:
- README.md

description: Advent of Code in Haskell

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- BangPatterns
- BlockArguments
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- QuasiQuotes
- TupleSections

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- multiset
- optparse-applicative
- pqueue
- search-algorithms
- split
- text

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    when:
    - condition: false
      other-modules: Paths_aoc

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - hspec
    - hspec-discover
    - raw-strings-qq
