name:                aoc-core
version:             0.1.0.0
github:              "drewolson/aoc/aoc-core"
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2022 Drew Olson"

description: Advent of Code in Haskell Core

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parallel

library:
  source-dirs: src

tests:
  aoc-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-core
    - hspec
    - hspec-discover
    - raw-strings-qq
    - QuickCheck
