name:                aoc-year2022
version:             0.1.0.0
github:              "drewolson/aoc/aoc-year2022"
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2022 Drew Olson"

description: Advent of Code in Haskell 2022

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- aoc-core
- containers
- megaparsec
- parallel
- search-algorithms
- split

library:
  source-dirs: src

tests:
  aoc-year2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-year2022
    - hspec
    - hspec-discover
    - raw-strings-qq
    - QuickCheck
