name: test

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: haskell:8.10.7-buster
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - run: stack test --allow-different-user
