name:                aoc-runner
version:             0.1.0.0
github:              "drewolson/aoc/aoc-runner"
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2022 Drew Olson"

description: Advent of Code in Haskell Runner

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- aoc-year2021
- aoc-year2022
- optparse-generic
- text

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-runner
    when:
    - condition: false
      other-modules: Paths_aoc_runner

tests:
  aoc-runner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-runner
    - hspec
    - hspec-discover
    - raw-strings-qq
    - QuickCheck
